name: Build

on:
  pull_request:
  workflow_call:

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3.0.0
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version-file: package.json
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test

      - name: Generate API report
        run: pnpm api

      - name: Commit API report
        uses: stefanzweifel/git-auto-commit-action@v5.0.1
        with:
          commit_message: "chore(api): update API report"
          file_pattern: "./etc/*.api.md"

  check-format:
    name: Check format
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3.0.0
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version-file: package.json
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Check format
        run: pnpm format:check

  check-lint:
    name: Check lint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3.0.0
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version-file: package.json
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Check lint
        run: pnpm lint
