name: Build
on:
  push:
jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.3

      - name: Setup pnpm
        uses: pnpm/action-setup@v3.0.0

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version-file: package.json
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

  check-format:
    name: Check format
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.3

      - name: Setup pnpm
        uses: pnpm/action-setup@v3.0.0

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version-file: package.json
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --dev

      - name: Check format
        run: pnpm format --check

  check-lint:
    name: Check lint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.3

      - name: Setup pnpm
        uses: pnpm/action-setup@v3.0.0

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version-file: package.json
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --dev

      - name: Check lint
        run: pnpm lint

  release:
    name: Release
    needs: [build, check-format, check-lint]
    permissions:
      contents: write # to create a GitHub release
      packages: write # to publish to the GitHub Package Registry
      issues: write # to comment on released issues
      pull-requests: write # to comment on released pull requests
    uses: ./.github/workflows/release.yml
    if: github.ref_type == 'branch' && github.ref_name == 'main'
